### ISSUE TITLE
[Bug] Footer not visible in "CC0 1.0"  TnC window

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [creativecommons/chooser#457] opened 2023-03-09 06:27 UTC
## Description
Footer is not completely visible in "CC0 1.0"  TnC window.

## Reproduction

1. In the first question "Do you know which license you need?" Choose option 2
2. In the second question "Do you want attribution for your work?" again choose option 2
3. Now you should be on the 6th step "Waive Your Copyright"
4. 
![image](https://user-images.githubusercontent.com/91469717/223938739-ceaf9e84-2544-435f-a265-5eb77f7c6c6f.png)
 
5. Click on "the terms and intended legal effect of CC0" link
7. scroll down to footer
8. See error.

## Expectation
It should be completely visible
or
It should be removed as it is not required

## Screenshots
![image](https://user-images.githubusercontent.com/91469717/223937530-b3802ec8-0e65-41c5-be12-b5270fd1c135.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by ZyX-N** [comment] 2023-03-09 20:59
I would like to work on this task, Can I get assign to this one ?

**Comment by Lakshay-Pruthi** [comment] 2023-03-10 06:07
@ZyX-N thanks for your interest in contributing to the project. But the issue is not yet approved.
 Please wait for a project maintainer to approve it
. Once the project maintainer has approved the issue then a PR can be raised.

You should go through the [Contribution Guideline](https://opensource.creativecommons.org/contributing-code/) to understand the labels.
 BTW as I have mentioned in the issue description that I would like to work on it. So, you may look at the other issues.

**Comment by possumbilities** [comment] 2023-03-10 20:36
@Lakshay-Pruthi Interesting find. The 1.0 info is an iframe that is embedding this page: https://creativecommons.org/publicdomain/zero/1.0/legalcode and the part it's cutting off is a link back to https://creativecommons.org/publicdomain/zero/1.0/ which in the context of the chooser in this way isn't necessary, so I would say that it being cut-off isn't hindering the overall use of the chooser as intended. 

I'm open to alternatives, but for now I'd say this can probably be closed.

**Closed by possumbilities** 2023-03-10 20:36 UTC
Labels: 🟧 priority: high, 🚦 status: awaiting triage, 🛠 goal: fix, 💻 aspect: code
