### ISSUE TITLE
Are the "Considerations Before Licensing" using the correct link?

### ISSUE THREAD

**Issue by fkohrt** [creativecommons/chooser#196] opened 2020-10-21 21:19 UTC
## Description

Currently the info modals regarding the "Considerations Before Licensing" links to the wiki page [Considerations for licensors and licensees](https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees). But there's also the [same (?) page on creativecommons.org](https://creativecommons.org/share-your-work/licensing-considerations/version4/).

Which one is the correct one? ~~In any case, the URL slug of the latter should probably be improved.~~

**Comment by Aspie96** [comment] 2020-11-30 22:44
Both are correct, but I think linking to the second one would be better, since creativecommons.org is more known and user friendly than the wiki.

**Comment by Yashs911** [comment] 2021-01-08 11:57
@fkohrt I would like to work on this issue

**Comment by obulat** [comment] 2021-01-08 12:43
While I completely agree that the creativecommons page is better in terms of user-friendliness, currently we cannot link to the specific section of the text there ('Consideration for licensEE/licensORs'), so I think until we add the section anchors on creativecommons.org, it's better to leave it as is.

**Comment by fkohrt** [comment] 2021-01-08 13:15
I originally raised the issue because I thought there might be differences in what is kept up to date. From a readability perspective I'd actually prefer to read the wiki page at the moment because it has a table of contents and more dense vertical spacing. I feel a little bit lost on the respective site at creativecommons.org.

**Comment by RATED-R-SUNDRAM** [comment] 2021-02-09 00:00
@fkohrt  I would like to work on this issue if no one else is currently working, can I?

**Comment by Cronus1007** [comment] 2021-02-09 01:15
>  it's better to leave it as is.
@RATED-R-SUNDRAM Since this issue has been labelled with `awaiting triage` so the issue is not ready for work yet.

**Comment by zackkrida** [comment] 2021-03-05 03:51
I am closing this issue as it is best to leave the links as-is. Thank you to everyone who put thought into this problem.

**Closed by zackkrida** 2021-03-05 03:51 UTC
Labels: 💻 aspect: code, 🚦 status: awaiting triage, 🛠 goal: fix, 🟧 priority: high
