### ISSUE TITLE
Long word in 'Attribution Details' step breaks the UI

### ISSUE THREAD

**Issue by soustab10** [creativecommons/chooser#463] opened 2023-03-11 16:01 UTC
## Description
If an user a long single word title (title without blankspaces) in 'Title of Work' or 'Creator of Work' under `Attribution Details` section, it results in increase of width of the `Mark Your Section` thereby breaking the UI. 

## Reproduction

1.  Step 1: Choose `Yes` in Step 1 and select any license.
2.  Step 2: In the `Title of Work` or `Creator of Work` section write a very long singular name  (Name without blankspaces). Adding any character (e.g. _ (underscore)) between words also works.
3. See error.

## Expectation
The width of the `Mark Your Section`  should not change rather the template should grow vertically.

### Desktop
![image](https://user-images.githubusercontent.com/95632583/224494261-98ff0fb3-9f45-4cf5-be00-00188c2fd601.png)

### Mobile
![image](https://user-images.githubusercontent.com/95632583/224494615-e40cc590-5eb3-4e12-bb22-6ce1960b3615.png)

## Environment

 - Device: All

## Additional context
This might be rare that user enters such an abnormal title, but it's possible and should be taken care of.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by UlbertAO** [comment] 2023-03-12 00:07
Hi,
can I work on this?

**Comment by soustab10** [comment] 2023-03-12 07:32
@UlbertAO  thanks for your interest to contribute on this project but it is not yet approved.
Please refer the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/) to understand the labels.
Also as mentioned in the issue description I would like to work on it. So, you may look at the other issues.

**Comment by possumbilities** [comment] 2023-03-20 20:47
@soustab10 Good find! Thank you.❤️ 

You've already had several helpful contributions. It might be better to let someone else work on a PR for this.

**Comment by soustab10** [comment] 2023-03-20 20:50
> @soustab10 Good find! Thank you.❤️
> 
> You've already had several helpful contributions. It might be better to let someone else work on a PR for this.

Okay @possumbilities ! Assign it to someone who's interested. I can fix it if it is not resolved after

**Comment by possumbilities** [comment] 2023-03-20 20:51
@UlbertAO Would you still like to work on this?

**Comment by AyushKaithwas** [comment] 2023-03-21 11:07
Hey I would like to work on this

**Comment by codewithmide** [comment] 2023-03-21 13:26
Hello Maintainers, I would love to take up this issue if it is not assigned to anyone yet.

**Comment by possumbilities** [comment] 2023-03-21 20:12
Passing along to @AyushKaithwas for now to work on. But it's fine to collab together if anyone wants to do that :)

**Comment by damlois** [comment] 2023-03-21 22:12
Hi @AyushKaithwas, would you want us to collaborate on this?

**Comment by codewithmide** [comment] 2023-03-22 05:44
> Hey I would like to work on this

Hi @AyushKaithwas are you willing to collaborate?

**Comment by AyushKaithwas** [comment] 2023-03-23 19:04
> Passing along to @AyushKaithwas for now to work on. But it's fine to collab together if anyone wants to do that :)

Hey, I have fixed the issue, please review.
https://github.com/creativecommons/chooser/pull/472

**Comment by AyushKaithwas** [comment] 2023-03-23 20:17
I have closed the pull request for now, because I found a better fix, I am implementing that

**Comment by UlbertAO** [comment] 2023-03-23 21:38
prevent right column from overflowing and word break on long text in … #[475](https://github.com/creativecommons/chooser/pull/475)

here is another fix for root cause of this issue

**Closed** 2023-03-31 20:40 UTC
Labels: 🟧 priority: high, 🏁 status: ready for work, 🛠 goal: fix, 💻 aspect: code
